

name: Run Database Migration
on:
  push:
    branches: 
      - master
env: 
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
  DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  SYNCHRONIZE_DB: ${{ secrets.SYNCHRONIZE_DB }}
  NODE_ENV: ${{ secrets.ENV }}

jobs:    
  migration:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Build entities
        run: |
          npm install
          npm run build

      - name: Generate migration
        id: generate-migration
        run: |
          npm run generate:migration

      - name: Run migration
        id: run-migration
        if: steps.generate-migration.outputs.migration_file != ''
        run: |
          npm run migration
      
    

  
